export const data = [
  {
    name: "Chanterelle",
    edible: "edible",
    season: "summer",
    description: "Golden-yellow, funnel-shaped mushroom with false gills",
    note: "Has toxic look-alikes - learn proper identification",
  },
  {
    name: "Morel",
    edible: "toxic",
    season: "spring",
    description: "Honeycomb-like cap, hollow inside",
    note: "Must be cooked before eating",
  },
  {
    name: "Chicken of the Woods",
    edible: "edible",
    season: "summer",
    description: "Bright orange bracket fungus with yellow edges",
    note: "Avoid if growing on certain tree species",
  },
  {
    name: "Death Cap",
    edible: "toxic",
    season: "summer",
    description: "Pale green to white cap with white gills",
    note: "Extremely toxic - study for safety awareness",
  },
  {
    name: "Oyster Mushroom",
    edible: "edible",
    season: "fall",
    description: "Fan-shaped caps growing in clusters",
    note: "Great beginner mushroom, few look-alikes",
  },
  {
    name: "Lion’s Mane",
    edible: "edible",
    season: "fall",
    description: "White, shaggy appearance like a lion's mane",
    note: "No toxic look-alikes",
  },
  {
    name: "Destroying Angel",
    edible: "toxic",
    season: "summer",
    description: "Pure white mushroom with a sack-like base",
    note: "Deadly toxic - study for safety awareness",
  },
  {
    name: "King Bolete",
    edible: "edible",
    season: "summer",
    description: "Large brown cap with thick stem",
    note: "Learn to distinguish from similar species",
  },
  {
    name: "Shaggy Mane",
    edible: "edible",
    season: "fall",
    description: "Tall white mushroom with shaggy scales",
    note: "Must be harvested and eaten quickly",
  },
  {
    name: "Maitake",
    edible: "edible",
    season: "fall",
    description: "Large, feathery clusters with overlapping gray-brown caps",
    note: "Also known as Hen of the Woods - no toxic look-alikes",
  },
  {
    name: "False Morel",
    edible: "toxic",
    season: "spring",
    description: "Brain-like, reddish-brown cap with irregular shape",
    note: "Highly toxic - often confused with true morels",
  },
  {
    name: "Matsutake",
    edible: "edible",
    season: "fall",
    description: "White to brown cap with thick stem and distinct spicy aroma",
    note: "Verify identification - has toxic look-alikes",
  },
  // ... add more mushrooms here
];
